-- seeds/news.sql


INSERT INTO `news`
    (`id`, `lga_id`, `lga_name`, `target_all_lgas`, `slug`, `title`, `summary`, `body`, `image_url`, `classification`, `category`, `breaking`, `source_url`, `source_name`, `author_id`, `status`, `views`, `published_at`, `created_at`, `updated_at`)
VALUES

(1, NULL, NULL, 1, 'governor-of-lagos-state-commits-to-empower-local-indigenes', 'Governor of Lagos State Commits to Empower Local Indigenes', 'Official updates from the administration regarding regional economic development and social welfare initiatives aimed at sustainable growth.', '<h2>A New Era of Empowerment</h2><p>The Lagos State Governor made a landmark commitment to empower local indigenes across all 20 LGAs, announcing a comprehensive package of social welfare and economic development programs. The initiative is expected to reach over <strong>2 million residents</strong> in the first phase.</p><h3>Skills Training &amp; Small Business</h3><p>Plans to support comprehensive vocational programs and micro-grants for local entrepreneurs. Over <strong>50,000 youths</strong> are expected to benefit from training centres to be established in each LGA.</p><ul><li>Digital skills and ICT training</li><li>Fashion design and tailoring</li><li>Welding, carpentry and construction trades</li><li>Agro-processing and food production</li></ul><p>A special Rural Access Roads Fund of &#8358;12 billion has been set aside for the 2025-2026 fiscal year.</p>', 'https://picsum.photos/seed/trending-gov/800/500', '["Official Announcement"]', 'Official Announcement', 1, 'https://example.com/news/1', 'Lagos State Government Portal', 101, 'published', 9821, '2025-05-13 06:00:00', '2025-05-13 06:00:00', NOW()),

(2, NULL, NULL, 1, 'new-solar-initiative-launches-across-lagos-lgas', 'New Solar Initiative Launches Across Lagos LGAs', 'The administration launches a region-wide renewable energy project to power 50 rural communities with clean energy by Q4 2025.', '<h2>Clean Energy for All</h2><p>Lagos State has announced a major solar energy rollout targeting underserved communities across all local government areas. The project, funded through a <strong>public-private partnership</strong>, will install solar micro-grids serving approximately <strong>50 rural communities</strong>.</p><ul><li>500 solar panels installed per community</li><li>24-hour power supply for health centres and schools</li><li>Local technicians to be trained for maintenance</li></ul>', 'https://picsum.photos/seed/trending-solar/800/500', '["Environment"]', 'Environment', 0, 'https://example.com/news/2', 'Lagos Energy Commission', 101, 'published', 7654, '2025-05-12 08:00:00', '2025-05-12 08:00:00', NOW()),

(3, NULL, NULL, 1, 'secondary-school-scholarship-programme-opens-applications', 'Secondary School Scholarship Programme Opens Applications', 'A new merit-based scholarship fund has been established to support high-achieving students from low-income households across Lagos.', '<h2>Investing in the Future</h2><p>The Lagos State Ministry of Education has officially opened applications for the <strong>2025 Secondary School Scholarship Programme</strong>. The fund will support <strong>500 students</strong> with full tuition coverage and monthly stipends of &#8358;15,000.</p><h3>Eligibility Criteria</h3><ul><li>Must be enrolled in a public secondary school in Lagos State</li><li>Minimum CGPA of 3.5 or equivalent grade average</li><li>Household income below &#8358;150,000 per month</li></ul><p>Deadline is <strong>June 30, 2025</strong>.</p>', 'https://picsum.photos/seed/trending-school/800/500', '["Education"]', 'Education', 0, 'https://example.com/news/3', 'Lagos State Ministry of Education', 102, 'published', 6210, '2025-05-11 10:00:00', '2025-05-11 10:00:00', NOW()),

(4, 11, 'Ikeja', 0, 'budget-transparency-town-hall-scheduled-for-june', 'Budget Transparency Town Hall Scheduled for June', 'Citizens are invited to participate in the upcoming virtual town hall to review the proposed 2026 LGA budget and provide feedback.', '<h2>Your Voice in the Budget</h2><p>In a move toward greater fiscal transparency, Ikeja LGA has announced a <strong>virtual town hall session</strong> to present and discuss the proposed 2026 budget. Citizens can submit questions in advance via the KTG Connect platform.</p><p>The session will be hosted on <em>June 14, 2025</em> at 10:00 AM and streamed live on the KTG Connect Reels section.</p><h3>Topics to be Covered</h3><ul><li>Infrastructure and road maintenance allocation</li><li>Health and education budget breakdown</li><li>Security and environmental sanitation</li><li>Community development projects</li></ul>', 'https://picsum.photos/seed/trending-budget/800/500', '["Engagement"]', 'Engagement', 0, 'https://example.com/news/4', 'Ikeja LGA Secretariat', 101, 'published', 5432, '2025-05-10 09:00:00', '2025-05-10 09:00:00', NOW()),

(5, 3, 'Alimosho', 0, 'alimosho-records-lowest-crime-rate-in-five-years', 'Alimosho Records Lowest Crime Rate in Five Years', 'Lagos State Police Command releases quarterly report showing significant drop in reported incidents across Alimosho.', '<h2>Safer Streets in Alimosho</h2><p>The Q1 2025 security report from the <strong>Lagos State Police Command</strong> highlights Alimosho as the most improved LGA in terms of crime reduction. Community policing initiatives and CCTV installations are credited for the improvement.</p><h3>Key Statistics</h3><ul><li>Armed robbery incidents down <strong>62%</strong> year-on-year</li><li>Petty theft reduced by <strong>48%</strong></li><li>Emergency response time improved from 18 minutes to <strong>7 minutes</strong></li></ul>', 'https://picsum.photos/seed/trending-crime/800/500', '["Security"]', 'Security', 0, 'https://example.com/news/5', 'Lagos State Police Command', 102, 'published', 4100, '2025-05-09 11:00:00', '2025-05-09 11:00:00', NOW()),

(6, 11, 'Ikeja', 0, 'power-restoration-18-hour-daily-supply-plan-takes-effect', 'Power Restoration: 18-Hour Daily Supply Plan Takes Effect', 'EKEDC announces new power distribution schedule guaranteeing minimum 18 hours of daily electricity supply to Ikeja residents.', '<h2>Light at the End of the Tunnel</h2><p>Eko Electricity Distribution Company (<strong>EKEDC</strong>) has commenced implementation of a new load management schedule designed to guarantee at least <strong>18 hours of electricity supply per day</strong> to residential and commercial customers in the Ikeja district.</p><ul><li>Residential zones: 6 AM to 12 AM (18 hours)</li><li>Commercial zones: 24-hour supply (priority grid)</li><li>Maintenance window: 12 AM to 6 AM</li></ul>', 'https://picsum.photos/seed/trending-power/800/500', '["Utilities"]', 'Utilities', 0, 'https://example.com/news/6', 'Eko Electricity Distribution Company', 103, 'published', 3870, '2025-05-08 14:00:00', '2025-05-08 14:00:00', NOW()),

(7, NULL, NULL, 1, 'lagos-state-water-project-phase-2-launch', 'Lagos State Water Project Phase 2 Launched', 'The second phase of the Lagos Water Renewal Project will bring potable water to 12 additional LGAs.', '<h2>Clean Water for All</h2><p>The Lagos State Ministry of Environment has officially launched Phase 2 of the Water Renewal Project, covering 12 underserved LGAs with new pipe networks and treatment facilities.</p>', 'https://picsum.photos/seed/trend7/800/500', '["Infrastructure"]', 'Infrastructure', 0, 'https://example.com/news/7', 'Lagos State Ministry of Environment', 101, 'published', 3200, '2025-05-07 08:00:00', '2025-05-07 08:00:00', NOW()),

(8, 11, 'Ikeja', 0, 'ikeja-road-resurfacing-project-commences', 'Ikeja Road Resurfacing Project Commences', 'Seven major roads in Ikeja are set to be resurfaced over the next 60 days as part of the urban renewal drive.', '<h2>Smoother Roads Ahead</h2><p>The Ikeja LGA Secretariat has announced commencement of the road resurfacing project covering seven arterial roads including Allen Avenue, Obafemi Awolowo Way, and Toyin Street.</p><ul><li>Allen Avenue</li><li>Obafemi Awolowo Way</li><li>Toyin Street</li><li>Joel Ogunnaike Street</li></ul>', 'https://picsum.photos/seed/trend8/800/500', '["Infrastructure"]', 'Infrastructure', 0, 'https://example.com/news/8', 'Ikeja LGA Secretariat', 102, 'published', 2900, '2025-05-06 10:00:00', '2025-05-06 10:00:00', NOW()),

(9, NULL, NULL, 1, 'lagos-free-wifi-zones-expansion-2025', 'Lagos Expands Free Public Wi-Fi to 50 New Locations', 'The Lagos Smart City initiative will deploy free high-speed public Wi-Fi across 50 new locations in Q3 2025.', '<h2>Digital Lagos</h2><p>As part of the Smart Lagos initiative, the state government has announced free public Wi-Fi deployment to 50 additional locations including bus terminals, markets, and community centres.</p>', 'https://picsum.photos/seed/trend9/800/500', '["Technology"]', 'Technology', 0, 'https://example.com/news/9', 'Lagos Smart City Office', 101, 'published', 2700, '2025-05-05 12:00:00', '2025-05-05 12:00:00', NOW()),

(10, NULL, NULL, 1, 'lagos-health-insurance-scheme-new-beneficiaries', 'Lagos Health Insurance Scheme Enrolls 100,000 New Beneficiaries', 'The Lagos State Health Management Agency has enrolled 100,000 new low-income residents into the state health insurance scheme.', '<h2>Healthcare for Everyone</h2><p>LASHMA has announced the successful enrollment of 100,000 additional beneficiaries under the Lagos State Health Insurance Scheme, bringing total coverage to over 800,000 residents.</p>', 'https://picsum.photos/seed/trend10/800/500', '["Health"]', 'Health', 0, 'https://example.com/news/10', 'LASHMA', 102, 'published', 2500, '2025-05-04 09:00:00', '2025-05-04 09:00:00', NOW()),

(11, 3, 'Alimosho', 0, 'alimosho-new-market-construction-begins', 'Alimosho New Central Market Construction Begins', 'Ground has finally been broken on the long-awaited Alimosho Central Market, which will accommodate over 2,000 traders.', '<h2>A Market for the People</h2><p>After months of anticipation, construction of the new Alimosho Central Market has officially commenced. The facility will host 2,000 stalls and include modern sanitation, cold storage, and security infrastructure.</p>', 'https://picsum.photos/seed/trend11/800/500', '["Economy"]', 'Economy', 0, 'https://example.com/news/11', 'Alimosho LGA Secretariat', 103, 'published', 2200, '2025-05-03 11:00:00', '2025-05-03 11:00:00', NOW()),

(12, NULL, NULL, 1, 'lagos-brt-expansion-six-new-routes', 'Lagos BRT Network Expands With Six New Routes', 'The Lagos Bus Rapid Transit network will add six new routes connecting underserved communities to commercial districts.', '<h2>Better Public Transport</h2><p>LAMATA has announced the addition of six new BRT routes to the existing network, covering areas including Badagry, Ikorodu, and Epe corridors.</p>', 'https://picsum.photos/seed/trend12/800/500', '["Infrastructure"]', 'Infrastructure', 0, 'https://example.com/news/12', 'LAMATA', 101, 'published', 2100, '2025-05-02 14:00:00', '2025-05-02 14:00:00', NOW()),

(13, NULL, NULL, 1, 'lagos-state-flood-early-warning-system', 'Lagos Deploys Flood Early Warning System Across 12 LGAs', 'A new flood early warning system using IoT sensors will alert residents up to 6 hours before flooding events.', '<h2>Protecting Lives</h2><p>The Lagos State Emergency Management Agency has deployed a network of IoT water-level sensors across 12 flood-prone LGAs. The system sends SMS and app alerts up to 6 hours before predicted flooding.</p>', 'https://picsum.photos/seed/trend13/800/500', '["Environment"]', 'Environment', 1, 'https://example.com/news/13', 'LASEMA', 102, 'published', 1900, '2025-05-01 08:00:00', '2025-05-01 08:00:00', NOW()),

(14, 11, 'Ikeja', 0, 'ikeja-community-policing-volunteers-recruited', 'Ikeja Recruits 500 Community Policing Volunteers', 'Ikeja LGA has recruited and trained 500 community policing volunteers to support safety across 20 wards.', '<h2>Community Safety First</h2><p>In a landmark security initiative, Ikeja LGA has recruited and completed basic training for 500 community policing volunteers. The volunteers will work alongside police officers in all 20 wards.</p>', 'https://picsum.photos/seed/trend14/800/500', '["Security"]', 'Security', 0, 'https://example.com/news/14', 'Ikeja LGA Security Committee', 103, 'published', 1700, '2025-04-30 10:00:00', '2025-04-30 10:00:00', NOW()),

(15, NULL, NULL, 1, 'lagos-state-youth-entrepreneurship-fund-2025', 'Lagos State Launches Youth Entrepreneurship Fund', 'Young entrepreneurs aged 18-35 can now apply for grants of up to 500,000 naira under the new state fund.', '<h2>Investing in Youth</h2><p>The Lagos State Employment Trust Fund has launched a youth entrepreneurship scheme. Grants of up to &#8358;500,000 are available for businesses in tech, agriculture, fashion, and food processing sectors.</p>', 'https://picsum.photos/seed/trend15/800/500', '["Economy"]', 'Economy', 0, 'https://example.com/news/15', 'LSETF', 101, 'published', 1600, '2025-04-29 09:00:00', '2025-04-29 09:00:00', NOW());