-- 002_create_users.sql
CREATE TABLE IF NOT EXISTS `users` (
    `id`                      INT           NOT NULL AUTO_INCREMENT,
    `name`                    VARCHAR(100)  NOT NULL,
    `email`                   VARCHAR(200)  NULL,
    `phone`                   VARCHAR(20)   NOT NULL,
    `password`                VARCHAR(255)  NOT NULL,
    `lga_id`                  INT           NULL,
    `lga_name`                VARCHAR(100)  NULL,
    `avatar_url`              VARCHAR(500)  NULL,
    `role`                    ENUM('citizen','admin') NOT NULL DEFAULT 'citizen',
    `is_verified`             BOOLEAN       NOT NULL DEFAULT FALSE,
    `status`                  ENUM('active','suspended','pending') NOT NULL DEFAULT 'pending',
    `has_seen_welcome`        BOOLEAN       NOT NULL DEFAULT FALSE,
    `profile_visibility`      ENUM('public','members','private') NOT NULL DEFAULT 'public',
    `two_fa_enabled`          BOOLEAN       NOT NULL DEFAULT FALSE,
    `notif_official`          BOOLEAN       NOT NULL DEFAULT TRUE,
    `notif_community`         BOOLEAN       NOT NULL DEFAULT TRUE,
    `notif_lga_alerts`        BOOLEAN       NOT NULL DEFAULT FALSE,
    `otp_code`                VARCHAR(10)   NULL,
    `otp_expires_at`          DATETIME      NULL,
    `reset_token`             VARCHAR(100)  NULL,
    `reset_token_expires_at`  DATETIME      NULL,
    `last_seen_at`            DATETIME      NULL,
    `created_at`              DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at`              DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_users_phone`       (`phone`),
    UNIQUE KEY `uq_users_email`       (`email`),
    UNIQUE KEY `uq_users_reset_token` (`reset_token`),
    INDEX `idx_users_lga_id`          (`lga_id`),
    INDEX `idx_users_status`          (`status`),
    INDEX `idx_users_last_seen`       (`last_seen_at`),
    CONSTRAINT `fk_users_lga` FOREIGN KEY (`lga_id`) REFERENCES `lgas` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
